version: '3.4'

services:
  rabbitmq:
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
  
  orderscheckoutservices.api.orders:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  orderscheckoutservices.notifications:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
